### ISSUE TITLE
Clarification on connection (host parameter should not contain the scheme )

### ISSUE THREAD

**Issue by johndpope** [nathanborror/swift-grpc#4]
I've been reviewing some other swift sample code

https://github.com/hosopy/grpc-mobile-demo-ios

& 

https://github.com/grpc/grpc/blob/master/src/objective-c/examples/SwiftSample/ViewController.swift

It seems there's some differences with your implementation
- host parameter should not contain the scheme (http:// or https://), only the name or IP addr
- and the port number, for example @"localhost:5050".

<img width="1196" alt="screen shot 2016-10-22 at 22 18 50" src="https://cloud.githubusercontent.com/assets/289994/19623747/91c5bca2-98a5-11e6-9aa4-437101783f42.png">

https://www.codatlas.com/github.com/grpc/grpc/master/src/objective-c/ProtoRPC/ProtoMethod.m
if I don't select a scheme - build crashes - which is fine.. just noteworthy.

Probably would make more sense to rename this project to server-side-swift-grpc as none of the code swift code is interchangeable (swift package manager can't run objective-c?) and so there's more merit in what you have achieved than simply swift grpc.

UPDATE
Looks like SPM can -  (doesn't mean it will work)
http://ankit.im/swift/2016/05/21/creating-objc-cpp-packages-with-swift-package-manager/

**Comment by nathanborror** [comment]
The scheme is needed to set `:scheme` HTTP/2 [header](https://github.com/nathanborror/swift-grpc/blob/master/Sources/gRPC.swift#L50) and determine if a TLS connection is [being used](https://github.com/nathanborror/swift-http2/blob/master/Sources/Http2.swift#L151) before instantiating the streams.

There shouldn't be anything server specific here, it's all pure swift and relying only on Foundation. I'm working on a full iOS client / web client / server / reverse-proxy server implementation here that may be helpful: https://github.com/nathanborror/pages
