### ISSUE TITLE
fyi - (hot off the press) https://github.com/grpc/grpc-swift

### ISSUE THREAD

**Issue by johndpope** [nathanborror/swift-grpc#6]

**Comment by nathanborror** [comment]
Cool. Have you tried it?

**Comment by johndpope** [comment]
I'm sure ios stuff will work.
ran into some troubles on ubuntu - working through them.
https://github.com/grpc/grpc-swift/issues/6

**Comment by johndpope** [comment]
hi @nathanborror - you asked if I had tested the above library. 
I finally got the service layer class generated with this library the other day. 
Went to plug it in to this 'hello world' tensorflow project https://github.com/nubbel/swift-tensorflow  - but the network calls are not so transparent and hitting walls / no so clear grpc server errors returned. sigh.....

tempted to rip out the hidden network calls and swap in your http2 classes (as opposed to using charles / wireshark).  
https://github.com/nubbel/swift-tensorflow/blob/master/Xcode/Test/AppDelegate.swift
